use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

def shared_pods
    pod 'Alamofire', '~> 4.3'
    pod 'SwiftyJSON'
    pod 'CocoaWSSE'
    pod 'FXBlurView', '~> 1.6'
    pod 'AHKActionSheet'
    pod 'DLAlertView'
    pod 'DownPicker'
    pod 'FXForms'
    pod 'RESideMenu', '~> 4.0.7'
    pod 'SlackTextViewController'
    pod 'JSQMessagesViewController'
    pod 'XMLDictionary'
    pod 'ASMediaFocusManager'
    pod 'IQKeyboardManagerSwift'
    pod 'Toast-Swift', '~> 3.0.1'
    pod 'PhoneNumberKit', '~> 2.1'
    pod 'EasyTipView', '~> 1.0.2'
    pod "RFAboutView-Swift", '~> 2.0.1'
    pod 'DateToolsSwift'
    pod 'GBVersionTracking'
    pod 'Chronos-Swift'
    pod 'SwiftDispatchOnce', '~> 1.0'
end

post_install do |installer|
  require 'fileutils'
  FileUtils.cp_r('Pods/Target Support Files/Pods-MyDailyBeat/Pods-MyDailyBeat-acknowledgements.plist', 'Acknowledgements.plist', :remove_destination => true)
end

target 'MyDailyBeat' do
    shared_pods
end

target 'API' do
    shared_pods
end
